name: All Builds (Linux, macOS, Windows, Android, APK, AAB)

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build-apk:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Android APK
        uses: flet-dev/flet-build-action@v1
        with:
          target: apk

      - uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/apk

  build-aab:
    name: Build Android AAB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Android AAB
        uses: flet-dev/flet-build-action@v1
        with:
          target: aab

      - uses: actions/upload-artifact@v4
        with:
          name: android-aab
          path: build/aab

  build-windows:
    name: Build Windows Executable
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Windows App
        uses: flet-dev/flet-build-action@v1
        with:
          target: windows

      - uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: build/windows

  build-linux:
    name: Build Linux Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Linux App
        uses: flet-dev/flet-build-action@v1
        with:
          target: linux

      - uses: actions/upload-artifact@v4
        with:
          name: linux-app
          path: build/linux

  build-macos:
    name: Build macOS App
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build macOS App
        uses: flet-dev/flet-build-action@v1
        with:
          target: macos

      - uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: build/macos
